# Site settings
title: Raspberry Pi AI
email: zack@hypercubeplatforms.com
description: > # this means to ignore newlines until "baseurl:"
  Raspberry Pi AI is devoted to cataloging the efforts to create a
  artificial intelligence using a Raspberry Pi with many features. Current
  features include face/speech recognition, poetry generation (creativity),
  motion sensing.
baseurl: "" # the subpath of your site, e.g. /blog
permalink: /:title/
url: "rpiai.com" # name of site e.g. localhost:4000
twitter_username: zack_118
github_username:  schollz

# Optionals
disqus_shortname: "rpiai"
google_analytics: "UA-2345677-6"

gems:
  - jekyll-sitemap

# Build settings
markdown: kramdown
